Gimme: fix the failures for building go1.5 & newer
   When set GIMME_TYPE=source or GIMME_TYPE=git,
   building go1.5 or newer version will be failed
   with error:
      I don't have any idea what to do with '1.5'.
    	 (using type 'source')
   or
      I don't have any idea what to do with '1.6'.
    	 (using type 'git')
   The bug was caused by unable to find the bootstrap.

   This patch will try to install the go1.4 binary as
   bootstrap before giving up.

Signed-off-by: lupan2005 <lupan2005@gmail.com>

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -185,9 +185,14 @@ _compile() {
 				fi
 			done
 			if [ -z "${bootstrap_root}" ] ; then
-				echo >&2 "error: Missing bootstrap installation"
-				echo >&2 "error: Unable to compile go from git clone"
-				return 1
+				if _try_binary "1.4" "${GIMME_HOSTARCH}" ; then
+					bootstrap_root="${GIMME_ENV_PREFIX}/go1.4.${GIMME_OS}.${GIMME_HOSTARCH}.env";
+					ln -sf "${GIMME_VERSION_PREFIX}/go1.4.${GIMME_OS}.${GIMME_HOSTARCH}" $HOME/go1.4;
+				else
+					echo >&2 "error: Unable to install go bootstrap";
+					echo >&2 "error: Missing bootstrap installation";
+					return 1;
+				fi
 			fi
 			export GOROOT_BOOTSTRAP="$(source "${bootstrap_root}" 2>/dev/null && go env GOROOT)"
 		fi
