Gimme: add GIMME_CC_FOR_TARGET for cross compiler
   When cross compiling is enabled (CGO_ENABLED=1),
   a proper C compiler has to be specified also if
   the GIMME_ARCH is not x86 neither x86_64.
   This patch added GIMME_CC_FOR_TARGET to allow user
   to specify the cross compiler for none x86 and
   none x86_64 architectures when CGO_ENABLED=1. It
   will set the default GIMME_CC_FOR_TAGET for arm64
   when CGO_ENABLED=1 and GIMME_OS=linux.
   This patch re-ordered the command line parameter
   handlng to make it more clean.

Signed-off-by: lupan2005 <lupan2005@gmail.com>

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -26,6 +26,7 @@
 #+        GIMME_ENV_PREFIX - prefix for env files (default '${GIMME_ENV_PREFIX}')
 #+     GIMME_GO_GIT_REMOTE - git remote for git-based install (default '${GIMME_GO_GIT_REMOTE}')
 #+                GIMME_OS - os to install (default '${GIMME_OS}')
+#+     GIMME_CC_FOR_TARGET - cross compiler for CGO_ENABLED=1
 #+               GIMME_TMP - temp directory (default '${GIMME_TMP}')
 #+              GIMME_TYPE - install type to perform ('auto', 'binary', 'source', or 'git')
 #+                           (default '${GIMME_TYPE}')
@@ -202,6 +203,7 @@ _compile() {
 		fi
 		cd src
 		export GOOS="${GIMME_OS}" GOARCH="${GIMME_ARCH}"
+		export CC_FOR_TARGET="${GIMME_CC_FOR_TARGET}"
 		local make_log="${1}/make.${GOOS}.${GOARCH}.log"
 		./make.bash &> $make_log || return 1
 	)
@@ -371,27 +373,7 @@ _assert_version_given() {
 : ${GIMME_TYPE:=auto} # 'auto', 'binary', 'source', or 'git'
 : ${GIMME_BINARY_OSX:=osx10.8}
 
-if [[ -n "${1}" ]] ; then
-	GIMME_GO_VERSION="${1}"
-fi
-if [[ -n "${2}" ]] ; then
-	GIMME_VERSION_PREFIX="${2}"
-fi
-
-case "${GIMME_ARCH}" in
-	x86_64) GIMME_ARCH=amd64 ;;
-	x86) GIMME_ARCH=386 ;;
-	arm64) ;;
-	arm*) GIMME_ARCH=arm ;;
-esac
-
-case "${GIMME_HOSTARCH}" in
-	x86_64) GIMME_HOSTARCH=amd64 ;;
-	x86) GIMME_HOSTARCH=386 ;;
-	arm64) ;;
-	arm*) GIMME_HOSTARCH=arm ;;
-esac
-
+force_flag=""
 case "${1}" in
 	-h|--help|help|wat)
 		_old_ifs="$IFS"
@@ -415,22 +397,54 @@ case "${1}" in
 		exit 0
 	;;
 	-f|--force|force)
-		GIMME_GO_VERSION="${2}"
-		if [[ -n "${3}" ]] ; then
-			GIMME_VERSION_PREFIX="${3}"
-		fi
-		_assert_version_given "$@"
-		_wipe_version "${GIMME_GO_VERSION}"
+		force_flag="force"
+		shift
 	;;
 esac
 
+if [[ -n "${1}" ]] ; then
+	GIMME_GO_VERSION="${1}"
+fi
+
+if [[ -n "${2}" ]] ; then
+	GIMME_VERSION_PREFIX="${2}"
+fi
+
 _assert_version_given "$@"
+
+case "${GIMME_ARCH}" in
+	x86_64) GIMME_ARCH=amd64 ;;
+	x86) GIMME_ARCH=386 ;;
+	arm64)
+		if [[ "${GIMME_GO_VERSION}" < "1.5.3" ]]; then
+			echo >&2 "error: arm64 is not supported by this go version"
+			echo >&2 "try go1.5.3 and newer version"
+			exit 1
+		fi
+		if [[ "${CGO_ENABLED}" == "1" && "${GIMME_OS}" == "linux" && "${GIMME_CC_FOR_TARGET}" == ""  ]]; then
+			GIMME_CC_FOR_TARGET="aarch64-linux-gnu-gcc"
+		fi
+		;;
+	arm*) GIMME_ARCH=arm ;;
+esac
+
+case "${GIMME_HOSTARCH}" in
+	x86_64) GIMME_HOSTARCH=amd64 ;;
+	x86) GIMME_HOSTARCH=386 ;;
+	arm64) ;;
+	arm*) GIMME_HOSTARCH=arm ;;
+esac
+
+if [[ "${force_flag}" == "force" ]] ; then
+	_wipe_version "${GIMME_GO_VERSION}"
+fi
 
 unset GOARCH
 unset GOBIN
 unset GOOS
 unset GOPATH
 unset GOROOT
+unset CC_FOR_TARGET
 
 mkdir -p "${GIMME_VERSION_PREFIX}" "${GIMME_ENV_PREFIX}"
 
